### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by bigshusha** [alexkuk/Ak_NovaPoshta#2]
Нова Пошта перешла на API 2.0. Будет ли продолжатся разработка?

**Comment by alexkuk** [comment]
К сожалению, у меня в ближайшее время заняться этим не получится. Кто желает, добро пожаловать поконтрибутить :)

**Comment by bigshusha** [comment]
Прогнозируете заняться в ближайшем будущем?

**Comment by alexkuk** [comment]
В ближайшее время заняться новым API не получится
